### ISSUE TITLE
Métricas

### ISSUE THREAD

**Issue by diegomvh** [UNPSJB/ids3t#11]
Incorporar las métricas detectadas

**Comment by diegocarabajal** [comment]
Incorporar al manual de calidad las métricas detectadas durante la confección del “Informe de calidad de software para el sistema Fuhrmann S.A.” en el marco del trabajo práctico de la Instancia supervisada de práctica profesional (ISFPP) de la materia Ingeniería de Software III-T del año 2016

**Comment by diegocarabajal** [comment]
Además de agregar a la complejidad ciclomática, introduje en la sección herramientas del apartado "Codificación y Producción de Contenido" a la herramienta Radon.

**Comment by diegomvh** [comment]
Complejidad ciclomática apunta a buscar la complejidad en el diseño de componentes, quizá seria mejor mover esa descripción a la parte de diseño
[Presentacin Exposicion pruebas.pdf](https://github.com/UNPSJB/ids3t/files/818862/Presentacin.Exposicion.pruebas.pdf)

**Comment by diegocarabajal** [comment]
Comparto link sobre la mantenibilidad del software: http://sistemas.unla.edu.ar/sistemas/redisla/ReLAIS/relais-v3-n6-231-236.pdf
