### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by diegomvh** [UNPSJB/ids3t#14]
El nombre correcto es manual de calidad

**Comment by diegocarabajal** [comment]
Gestionar el cambio de nombre pasando de "Plan de Aseguramiento de la Calidad de Software" a "Manual de Calidad"

**Comment by diegomvh** [comment]
En varios lugares del documento se menciona al **Plan** de calidad, cuando lo correcto seria referirnos al **Manual** de calidad.
Particularmente el titulo correcto seria **Manual de Aseguramiento de la Calidad de Software**
Y la ruta correcta **ManualSQA**
Conversando con Gloria el planteo es simple, un *Plan* es una instancia de un *Manual* de calidad aplicado.

**Comment by diegomvh** [comment]
Quedan por ver aquellos lugares donde dice plan en lugar de manual, pero el titulo ya esta.
