### ISSUE TITLE
Requisitos no funcionales

### ISSUE THREAD

**Issue by diegomvh** [UNPSJB/ids3t#9]
Incorporar al plan de QA las temáticas referidas a los requisitos no funcionales

**Comment by diegocarabajal** [comment]
Incorporar al plan de QA (Qualitty Assurance) un apartado sobre requerimientos no funcionales, en el cual se especifiquen los procesos y las buenas prácticas que propenden a la calidad en los procesos de producción de software.

**Comment by diegomvh** [comment]
Introduce no funcionales desde la descripción, a futuro resta evaluar como integrarlo mejor con el apartado de **Ingeniería de Requerimientos** y entender el caso particular de estos requerimientos y sus condiciones particulares

**Comment by diegocarabajal** [comment]
En este link figura una check list sobre requisitos no funcionales: http://leadinganswers.typepad.com/files/non-functional-requiements.pdf
